version: '2'
services:
  ca-certificates:
    image: registry.gitlab.com/kalaksi-containers/ca-certificates
    # Getting the image from GitLab is recommended but Docker Hub works too:
    # image: docker.io/kalaksi/ca-certificates
    restart: 'no'
    cap_drop:
      - ALL
    volumes:
      - cert-store:/etc/ssl/certs
    # environment:
    #   CA_CERT_0_NAME: example-ca-cert
    #   CA_CERT_0: |
    #     -----BEGIN CERTIFICATE-----
    #     ...
    #     -----END CERTIFICATE-----

volumes:
  cert-store: {}
