version: '2'
services:
  ca-certificates:
    image: kalaksi/ca-certificates
    restart: 'no'
    cap_drop:
      - ALL
    volumes:
      - cert-store:/etc/ssl/certs
    # environment:
    #   CA_CERT_0_NAME: example-ca-cert
    #   CA_CERT_0: |
    #     -----BEGIN CERTIFICATE-----
    #     ...
    #     -----END CERTIFICATE-----

# TODO: add an example of a service using this volume
volumes:
  cert-store: {}
